const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('scriptureAPI', {
  search: (query, version) => ipcRenderer.invoke('search:query', { query, version }),
  searchAllVersions: (query) => ipcRenderer.invoke('search:reference-all-versions', { query }),
  listVersions: () => ipcRenderer.invoke('search:versions'),
  listBooks: () => ipcRenderer.invoke('search:books'),
  getDbError: () => ipcRenderer.invoke('diagnostics:db-error'),
  getState: () => ipcRenderer.invoke('state:get'),
  addToSchedule: (item) => ipcRenderer.invoke('schedule:add', item),
  removeFromSchedule: (id) => ipcRenderer.invoke('schedule:remove', id),
  moveSchedule: (id, direction) => ipcRenderer.invoke('schedule:move', { id, direction }),
  setPreview: (item) => ipcRenderer.invoke('preview:set', item),
  goLive: (item) => ipcRenderer.invoke('live:go', item),
  blackLive: () => ipcRenderer.invoke('live:black'),
  restoreLive: () => ipcRenderer.invoke('live:restore'),
  clearLiveState: () => ipcRenderer.invoke('live:clear-state'),
  onStateUpdate: (callback) => ipcRenderer.on('state:update', (e, snapshot) => callback(snapshot)),
  openLiveWindow: () => ipcRenderer.send('live:open'),
  setLiveTheme: (theme) => ipcRenderer.send('live:set-theme', theme),
  selectBackgroundImage: () => ipcRenderer.invoke('theme:select-image'),
  ndiStatus: () => ipcRenderer.invoke('ndi:status'),
  ndiStart: () => ipcRenderer.invoke('ndi:start'),
  ndiStop: () => ipcRenderer.invoke('ndi:stop'),
  getRemoteInfo: () => ipcRenderer.invoke('remote:info'),
  onLiveUpdate: (callback) => ipcRenderer.on('live:update', (e, payload) => callback(payload)),
  onLiveClear: (callback) => ipcRenderer.on('live:clear', () => callback()),
  onLiveTheme: (callback) => ipcRenderer.on('live:theme', (e, theme) => callback(theme)),
  onLiveDisplay: (callback) => ipcRenderer.on('live:display', (e, snapshot) => callback(snapshot)),
});
