// Local network server for the mobile Remote.
const express=require('express');const cors=require('cors');const http=require('http');const path=require('path');const fs=require('fs');const {WebSocketServer}=require('ws');
function startServer({state,search,port=3939}){
 const app=express();app.disable('x-powered-by');app.use(cors({origin:true}));app.use(express.json({limit:'512kb'}));app.use(express.static(path.join(__dirname,'public'),{etag:false,maxAge:0}));
 const serviceDir=path.join(__dirname,'services');if(!fs.existsSync(serviceDir))fs.mkdirSync(serviceDir,{recursive:true});
 const resolveItem=(item)=>{if(!item||item.type!=='scripture'||!item.reference)return item;const ref=search.parseReference(String(item.reference));if(!ref)return item;const rows=search.getByReference(ref,state.snapshot().selectedVersion);return rows.length?{...item,version:state.snapshot().selectedVersion,text:rows.map(r=>r.text).join(' ')}:{...item,version:state.snapshot().selectedVersion};};
 app.get('/api/health',(req,res)=>res.json({ok:true,service:'Scripture Remote',output:state.snapshot().output,selectedVersion:state.snapshot().selectedVersion,ndi:false}));
 app.get('/api/state',(req,res)=>res.json(state.snapshot()));
 app.post('/api/version',(req,res)=>{const version=String(req.body?.version||'');if(!version)return res.status(400).json({error:'version is required'});state.setVersion(version,(reference,selected)=>{const ref=search.parseReference(reference);return ref?search.getByReference(ref,selected):[];});res.json({ok:true,selectedVersion:state.snapshot().selectedVersion});});
 app.get('/api/versions',(req,res)=>res.json(search.listVersions()));
 app.get('/api/search',(req,res)=>{const{q,version}=req.query;if(!q||!version)return res.status(400).json({error:'q and version are required'});try{return res.json(search.search(String(q),String(version)));}catch(e){return res.status(500).json({error:e.message});}});
 app.get('/api/search-all',(req,res)=>{const ref=search.parseReference(String(req.query.q||''));if(!ref)return res.status(400).json({error:'Could not parse a reference from that input.'});res.json({reference:ref,versions:search.getByReferenceAllVersions(ref)});});
 app.post('/api/schedule',(req,res)=>{const entry=state.addToSchedule(resolveItem(req.body));if(!entry)return res.status(400).json({error:'Invalid schedule item.'});res.json(entry);});
 app.delete('/api/schedule/:id',(req,res)=>{state.removeFromSchedule(req.params.id);res.json({ok:true});});app.post('/api/schedule/:id/move',(req,res)=>{state.moveInSchedule(req.params.id,req.body.direction);res.json({ok:true});});
 app.post('/api/preview',(req,res)=>{state.setPreview(resolveItem(req.body));res.json({ok:true});});app.post('/api/go-live',(req,res)=>{state.goLive(resolveItem(req.body));res.json({ok:true});});
 app.post('/api/black',(req,res)=>{state.blackout();res.json({ok:true,output:'black'});});app.post('/api/restore',(req,res)=>{state.restoreLive();res.json({ok:true,output:state.snapshot().output});});app.post('/api/clear',(req,res)=>{state.clearLive();res.json({ok:true,output:'clear'});});
 app.post('/api/theme',(req,res)=>{state.setTheme(req.body);res.json({ok:true});});app.post('/api/transition',(req,res)=>{state.setTransition(req.body?.transition);res.json({ok:true,transition:state.snapshot().transition});});app.post('/api/stage-mode',(req,res)=>{state.setStageMode(req.body?.mode);res.json({ok:true,stageMode:state.snapshot().stageMode});});
 app.get('/api/services',(req,res)=>{const files=fs.readdirSync(serviceDir).filter(f=>f.endsWith('.json')).map(f=>f.slice(0,-5));res.json(files);});
 app.post('/api/services',(req,res)=>{const name=String(req.body?.name||'Untitled Service').replace(/[^a-z0-9 _-]/gi,'').trim()||'Untitled Service';const payload={name,schedule:state.snapshot().schedule,selectedVersion:state.snapshot().selectedVersion,theme:state.snapshot().theme,transition:state.snapshot().transition,stageMode:state.snapshot().stageMode,savedAt:new Date().toISOString()};fs.writeFileSync(path.join(serviceDir,`${name}.json`),JSON.stringify(payload,null,2));state.setServiceName(name);res.json(payload);});
 app.get('/api/services/:name',(req,res)=>{const safe=String(req.params.name).replace(/[^a-z0-9 _-]/gi,'');const file=path.join(serviceDir,`${safe}.json`);if(!fs.existsSync(file))return res.status(404).json({error:'Service not found'});res.json(JSON.parse(fs.readFileSync(file,'utf8')));});
 app.post('/api/services/:name/load',(req,res)=>{const safe=String(req.params.name).replace(/[^a-z0-9 _-]/gi,'');const file=path.join(serviceDir,`${safe}.json`);if(!fs.existsSync(file))return res.status(404).json({error:'Service not found'});const s=JSON.parse(fs.readFileSync(file,'utf8'));state.setServiceName(s.name);state.replaceSchedule(s.schedule||[]);if(s.selectedVersion)state.setVersion(s.selectedVersion,(reference,selected)=>{const ref=search.parseReference(reference);return ref?search.getByReference(ref,selected):[];});if(s.theme)state.setTheme(s.theme);if(s.transition)state.setTransition(s.transition);if(s.stageMode)state.setStageMode(s.stageMode);res.json(state.snapshot());});
 const httpServer=http.createServer(app);const wss=new WebSocketServer({server:httpServer,perMessageDeflate:false});const broadcastState=()=>{const payload=JSON.stringify({type:'state',data:state.snapshot()});for(const client of wss.clients)if(client.readyState===1)client.send(payload);};state.on('change',broadcastState);wss.on('connection',ws=>{ws.send(JSON.stringify({type:'state',data:state.snapshot()}));ws.on('error',()=>{});});
 return new Promise((resolve,reject)=>{httpServer.once('error',reject);httpServer.listen(port,'0.0.0.0',()=>resolve({httpServer,port}));});
}
module.exports={startServer};
